'use client'

import { useEffect, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

/**
 * LogoIntro — 4TP brand entrance animation.
  *
   * Sequence (OuiOui001-inspired pacing, square version):
    *   0ms    — Black screen
     *   300ms  — Small yellow square pulses in (center screen)
      *   1000ms — Square rapidly expands to fill screen
       *   1400ms — "4" fades in, "TP" slides in
        *   2200ms — Logo holds
         *   2800ms — Overlay slides UP off screen, revealing hero below
          *   3600ms — Component unmounts (cleanup)
           */
           
           const EASE_EXPO = [0.76, 0, 0.24, 1] as const
           const EASE_SPRING = [0.16, 1, 0.3, 1] as const
           
           type Phase = 'square' | 'expand' | 'logo' | 'exit'
           
           export default function LogoIntro() {
             const [phase, setPhase] = useState<Phase>('square')
               const [visible, setVisible] = useState(true)
               
                 useEffect(() => {
                     const t1 = setTimeout(() => setPhase('expand'), 600)
                         const t2 = setTimeout(() => setPhase('logo'), 1200)
                             const t3 = setTimeout(() => setPhase('exit'), 2500)
                                 const t4 = setTimeout(() => setVisible(false), 3400)
                                     return () => [t1, t2, t3, t4].forEach(clearTimeout)
                                       }, [])
                                       
                                         return (
                                             <AnimatePresence>
                                                   {visible && (
                                                           <motion.div
                                                                     key="logo-intro-overlay"
                                                                               className="fixed inset-0 z-[200] flex items-center justify-center overflow-hidden"
                                                                                         style={{ backgroundColor: '#0A0A0A' }}
                                                                                                   animate={
                                                                                                               phase === 'exit'
                                                                                                                             ? { y: '-100%' }
                                                                                                                                           : { y: 0 }
                                                                                                                                                     }
                                                                                                                                                               transition={
                                                                                                                                                                           phase === 'exit'
                                                                                                                                                                                         ? { duration: 0.75, ease: EASE_EXPO }
                                                                                                                                                                                                       : { duration: 0 }
                                                                                                                                                                                                                 }
                                                                                                                                                                                                                         >
                                                                                                                                                                                                                                   {/* Yellow square — starts tiny, expands to fill screen */}
                                                                                                                                                                                                                                             <motion.div
                                                                                                                                                                                                                                                         className="absolute flex items-center justify-center"
                                                                                                                                                                                                                                                                     style={{ backgroundColor: '#FEEB3D' }}
                                                                                                                                                                                                                                                                                 initial={{ width: 80, height: 80, borderRadius: 4 }}
                                                                                                                                                                                                                                                                                             animate={
                                                                                                                                                                                                                                                                                                           phase === 'square'
                                                                                                                                                                                                                                                                                                                           ? { width: 80, height: 80, borderRadius: 4 }
                                                                                                                                                                                                                                                                                                                                           : phase === 'expand' || phase === 'logo' || phase === 'exit'
                                                                                                                                                                                                                                                                                                                                                           ? { width: 3000, height: 3000, borderRadius: 0 }
                                                                                                                                                                                                                                                                                                                                                                           : { width: 80, height: 80, borderRadius: 4 }
                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                   transition={
                                                                                                                                                                                                                                                                                                                                                                                                                 phase === 'expand' || phase === 'logo' || phase === 'exit'
                                                                                                                                                                                                                                                                                                                                                                                                                                 ? { duration: 0.65, ease: EASE_EXPO }
                                                                                                                                                                                                                                                                                                                                                                                                                                                 : { duration: 0.4, ease: EASE_SPRING }
                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {/* Logo content — centered on top of the yellow fill */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div className="relative z-10 flex items-center gap-2 select-none">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {/* "4" in black */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <motion.span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fontFamily: 'Inter, sans-serif',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fontWeight: 900,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fontSize: 'clamp(4rem, 12vw, 10rem)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 color: '#0A0A0A',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 lineHeight: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 letterSpacing: '-0.04em',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             initial={{ opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           animate={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           opacity: phase === 'logo' || phase === 'exit' ? 1 : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       transition={{ duration: 0.3, ease: EASE_SPRING }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </motion.span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {/* "TP" slides in from right */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <motion.span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fontFamily: 'Inter, sans-serif',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fontWeight: 900,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fontSize: 'clamp(4rem, 12vw, 10rem)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   color: '#0A0A0A',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   lineHeight: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   letterSpacing: '-0.04em',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               initial={{ opacity: 0, x: 48 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             animate={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             opacity: phase === 'logo' || phase === 'exit' ? 1 : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             x: phase === 'logo' || phase === 'exit' ? 0 : 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         transition={{ duration: 0.45, ease: EASE_SPRING, delay: 0.1 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   TP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </motion.span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </AnimatePresence>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }